# hello-go-deploy-azure-vm task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: hello-go-deploy-azure-vm

outputs:
- name: hello-go-deploy-azure-vm-updated

run:
  path: ./hello-go-deploy-azure-vm/ci/scripts/readme-github-pages.sh
  # args: [-debug]

