# hello-go-deploy-azure-vm task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-azure-vm

outputs:
- name: coverage-results

run:
  path: ./hello-go-deploy-azure-vm/ci/scripts/unit-tests.sh
  # args: [-debug]
  