# hello-go-deploy-azure-vm task-build-push.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-azure-vm

outputs:
- name: dist

run:
  path: ./hello-go-deploy-azure-vm/ci/scripts/build-push.sh
  # args: [-debug]

